-- Create Jobworker table
CREATE TABLE IF NOT EXISTS public.jobworker (
    jobworker_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jobworker_name TEXT NOT NULL,
    place TEXT,
    cell_no TEXT
);

-- Comments to describe columns
COMMENT ON COLUMN public.jobworker.jobworker_id IS 'Unique identifier for each jobworker';
COMMENT ON COLUMN public.jobworker.jobworker_name IS 'Name of the jobworker';
COMMENT ON COLUMN public.jobworker.place IS 'Location or place of the jobworker';
COMMENT ON COLUMN public.jobworker.cell_no IS 'Contact number of the jobworker';
